// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package annict

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type ActivityItem interface {
	IsActivityItem()
}

// An object with an ID.
type Node interface {
	IsNode()
	// ID of the object.
	GetID() string
}

type StaffResourceItem interface {
	IsStaffResourceItem()
}

type Activity struct {
	AnnictID int64 `json:"annictId"`
	// ID of the object.
	ID   string `json:"id"`
	User *User  `json:"user"`
}

func (Activity) IsNode() {}

// ID of the object.
func (this Activity) GetID() string { return this.ID }

// The connection type for Activity.
type ActivityConnection struct {
	// A list of edges.
	Edges []*ActivityEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Activity `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type ActivityEdge struct {
	Action   ActivityAction `json:"action"`
	AnnictID int64          `json:"annictId"`
	// A cursor for use in pagination.
	Cursor string       `json:"cursor"`
	Item   ActivityItem `json:"item,omitempty"`
	// The item at the end of the edge.
	Node *Activity `json:"node,omitempty"`
	User *User     `json:"user"`
}

type ActivityOrder struct {
	Direction OrderDirection     `json:"direction"`
	Field     ActivityOrderField `json:"field"`
}

type Cast struct {
	AnnictID   int64      `json:"annictId"`
	Character  *Character `json:"character"`
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	NameEn     string     `json:"nameEn"`
	Person     *Person    `json:"person"`
	SortNumber int64      `json:"sortNumber"`
	Work       *Work      `json:"work"`
}

func (Cast) IsNode() {}

// ID of the object.
func (this Cast) GetID() string { return this.ID }

// The connection type for Cast.
type CastConnection struct {
	// A list of edges.
	Edges []*CastEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Cast `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type CastEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Cast `json:"node,omitempty"`
}

type CastOrder struct {
	Direction OrderDirection `json:"direction"`
	Field     CastOrderField `json:"field"`
}

type Channel struct {
	AnnictID     int64              `json:"annictId"`
	ChannelGroup *ChannelGroup      `json:"channelGroup"`
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Programs     *ProgramConnection `json:"programs,omitempty"`
	Published    bool               `json:"published"`
	ScChid       int64              `json:"scChid"`
}

func (Channel) IsNode() {}

// ID of the object.
func (this Channel) GetID() string { return this.ID }

// The connection type for Channel.
type ChannelConnection struct {
	// A list of edges.
	Edges []*ChannelEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Channel `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type ChannelEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Channel `json:"node,omitempty"`
}

type ChannelGroup struct {
	AnnictID   int64              `json:"annictId"`
	Channels   *ChannelConnection `json:"channels,omitempty"`
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	SortNumber int64              `json:"sortNumber"`
}

func (ChannelGroup) IsNode() {}

// ID of the object.
func (this ChannelGroup) GetID() string { return this.ID }

type Character struct {
	Age                     string  `json:"age"`
	AgeEn                   string  `json:"ageEn"`
	AnnictID                int64   `json:"annictId"`
	Birthday                string  `json:"birthday"`
	BirthdayEn              string  `json:"birthdayEn"`
	BloodType               string  `json:"bloodType"`
	BloodTypeEn             string  `json:"bloodTypeEn"`
	Description             string  `json:"description"`
	DescriptionEn           string  `json:"descriptionEn"`
	DescriptionSource       string  `json:"descriptionSource"`
	DescriptionSourceEn     string  `json:"descriptionSourceEn"`
	FavoriteCharactersCount int64   `json:"favoriteCharactersCount"`
	Height                  string  `json:"height"`
	HeightEn                string  `json:"heightEn"`
	ID                      string  `json:"id"`
	Name                    string  `json:"name"`
	NameEn                  string  `json:"nameEn"`
	NameKana                string  `json:"nameKana"`
	Nationality             string  `json:"nationality"`
	NationalityEn           string  `json:"nationalityEn"`
	Nickname                string  `json:"nickname"`
	NicknameEn              string  `json:"nicknameEn"`
	Occupation              string  `json:"occupation"`
	OccupationEn            string  `json:"occupationEn"`
	Series                  *Series `json:"series,omitempty"`
	Weight                  string  `json:"weight"`
	WeightEn                string  `json:"weightEn"`
}

func (Character) IsNode() {}

// ID of the object.
func (this Character) GetID() string { return this.ID }

// The connection type for Character.
type CharacterConnection struct {
	// A list of edges.
	Edges []*CharacterEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Character `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type CharacterEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Character `json:"node,omitempty"`
}

type CharacterOrder struct {
	Direction OrderDirection      `json:"direction"`
	Field     CharacterOrderField `json:"field"`
}

// Autogenerated input type of CreateRecord
type CreateRecordInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string      `json:"clientMutationId,omitempty"`
	Comment          *string      `json:"comment,omitempty"`
	EpisodeID        string       `json:"episodeId"`
	RatingState      *RatingState `json:"ratingState,omitempty"`
	ShareFacebook    *bool        `json:"shareFacebook,omitempty"`
	ShareTwitter     *bool        `json:"shareTwitter,omitempty"`
}

// Autogenerated return type of CreateRecord.
type CreateRecordPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Record           *Record `json:"record,omitempty"`
}

// Autogenerated input type of CreateReview
type CreateReviewInput struct {
	Body string `json:"body"`
	// A unique identifier for the client performing the mutation.
	ClientMutationID     *string      `json:"clientMutationId,omitempty"`
	RatingAnimationState *RatingState `json:"ratingAnimationState,omitempty"`
	RatingCharacterState *RatingState `json:"ratingCharacterState,omitempty"`
	RatingMusicState     *RatingState `json:"ratingMusicState,omitempty"`
	RatingOverallState   *RatingState `json:"ratingOverallState,omitempty"`
	RatingStoryState     *RatingState `json:"ratingStoryState,omitempty"`
	ShareFacebook        *bool        `json:"shareFacebook,omitempty"`
	ShareTwitter         *bool        `json:"shareTwitter,omitempty"`
	Title                *string      `json:"title,omitempty"`
	WorkID               string       `json:"workId"`
}

// Autogenerated return type of CreateReview.
type CreateReviewPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Review           *Review `json:"review,omitempty"`
}

// Autogenerated input type of DeleteRecord
type DeleteRecordInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	RecordID         string  `json:"recordId"`
}

// Autogenerated return type of DeleteRecord.
type DeleteRecordPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
	Episode          *Episode `json:"episode,omitempty"`
}

// Autogenerated input type of DeleteReview
type DeleteReviewInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	ReviewID         string  `json:"reviewId"`
}

// Autogenerated return type of DeleteReview.
type DeleteReviewPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Work             *Work   `json:"work,omitempty"`
}

// An episode of a work
type Episode struct {
	AnnictID            int64             `json:"annictId"`
	ID                  string            `json:"id"`
	NextEpisode         *Episode          `json:"nextEpisode,omitempty"`
	Number              *int64            `json:"number,omitempty"`
	NumberText          *string           `json:"numberText,omitempty"`
	PrevEpisode         *Episode          `json:"prevEpisode,omitempty"`
	RecordCommentsCount int64             `json:"recordCommentsCount"`
	Records             *RecordConnection `json:"records,omitempty"`
	RecordsCount        int64             `json:"recordsCount"`
	SatisfactionRate    *float64          `json:"satisfactionRate,omitempty"`
	SortNumber          int64             `json:"sortNumber"`
	Title               *string           `json:"title,omitempty"`
	ViewerDidTrack      bool              `json:"viewerDidTrack"`
	ViewerRecordsCount  int64             `json:"viewerRecordsCount"`
	Work                *Work             `json:"work"`
}

func (Episode) IsNode() {}

// ID of the object.
func (this Episode) GetID() string { return this.ID }

// The connection type for Episode.
type EpisodeConnection struct {
	// A list of edges.
	Edges []*EpisodeEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Episode `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type EpisodeEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Episode `json:"node,omitempty"`
}

type EpisodeOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     EpisodeOrderField `json:"field"`
}

type LibraryEntry struct {
	ID          string   `json:"id"`
	NextEpisode *Episode `json:"nextEpisode,omitempty"`
	NextProgram *Program `json:"nextProgram,omitempty"`
	Note        string   `json:"note"`
	Status      *Status  `json:"status,omitempty"`
	User        *User    `json:"user"`
	Work        *Work    `json:"work"`
}

func (LibraryEntry) IsNode() {}

// ID of the object.
func (this LibraryEntry) GetID() string { return this.ID }

// The connection type for LibraryEntry.
type LibraryEntryConnection struct {
	// A list of edges.
	Edges []*LibraryEntryEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*LibraryEntry `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type LibraryEntryEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *LibraryEntry `json:"node,omitempty"`
}

type LibraryEntryOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     LibraryEntryOrderField `json:"field"`
}

type MultipleRecord struct {
	AnnictID  int64             `json:"annictId"`
	CreatedAt string            `json:"createdAt"`
	ID        string            `json:"id"`
	Records   *RecordConnection `json:"records,omitempty"`
	User      *User             `json:"user"`
	Work      *Work             `json:"work"`
}

func (MultipleRecord) IsActivityItem() {}

func (MultipleRecord) IsNode() {}

// ID of the object.
func (this MultipleRecord) GetID() string { return this.ID }

type Mutation struct {
}

type Organization struct {
	AnnictID                   int64   `json:"annictId"`
	FavoriteOrganizationsCount int64   `json:"favoriteOrganizationsCount"`
	ID                         string  `json:"id"`
	Name                       string  `json:"name"`
	NameEn                     string  `json:"nameEn"`
	NameKana                   string  `json:"nameKana"`
	StaffsCount                int64   `json:"staffsCount"`
	TwitterUsername            *string `json:"twitterUsername,omitempty"`
	TwitterUsernameEn          string  `json:"twitterUsernameEn"`
	URL                        *string `json:"url,omitempty"`
	URLEn                      string  `json:"urlEn"`
	WikipediaURL               *string `json:"wikipediaUrl,omitempty"`
	WikipediaURLEn             string  `json:"wikipediaUrlEn"`
}

func (Organization) IsNode() {}

// ID of the object.
func (this Organization) GetID() string { return this.ID }

func (Organization) IsStaffResourceItem() {}

// The connection type for Organization.
type OrganizationConnection struct {
	// A list of edges.
	Edges []*OrganizationEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Organization `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type OrganizationEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Organization `json:"node,omitempty"`
}

type OrganizationOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     OrganizationOrderField `json:"field"`
}

// Information about pagination in a connection.
type PageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor *string `json:"endCursor,omitempty"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue.
	StartCursor *string `json:"startCursor,omitempty"`
}

type Person struct {
	AnnictID            int64       `json:"annictId"`
	Birthday            *string     `json:"birthday,omitempty"`
	BloodType           *string     `json:"bloodType,omitempty"`
	CastsCount          int64       `json:"castsCount"`
	FavoritePeopleCount int64       `json:"favoritePeopleCount"`
	GenderText          *string     `json:"genderText,omitempty"`
	Height              *string     `json:"height,omitempty"`
	ID                  string      `json:"id"`
	Name                string      `json:"name"`
	NameEn              string      `json:"nameEn"`
	NameKana            string      `json:"nameKana"`
	Nickname            *string     `json:"nickname,omitempty"`
	NicknameEn          string      `json:"nicknameEn"`
	Prefecture          *Prefecture `json:"prefecture,omitempty"`
	StaffsCount         int64       `json:"staffsCount"`
	TwitterUsername     *string     `json:"twitterUsername,omitempty"`
	TwitterUsernameEn   string      `json:"twitterUsernameEn"`
	URL                 *string     `json:"url,omitempty"`
	URLEn               string      `json:"urlEn"`
	WikipediaURL        *string     `json:"wikipediaUrl,omitempty"`
	WikipediaURLEn      string      `json:"wikipediaUrlEn"`
}

func (Person) IsNode() {}

// ID of the object.
func (this Person) GetID() string { return this.ID }

func (Person) IsStaffResourceItem() {}

// The connection type for Person.
type PersonConnection struct {
	// A list of edges.
	Edges []*PersonEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Person `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type PersonEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Person `json:"node,omitempty"`
}

type PersonOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     PersonOrderField `json:"field"`
}

type Prefecture struct {
	AnnictID int64  `json:"annictId"`
	ID       string `json:"id"`
	Name     string `json:"name"`
}

func (Prefecture) IsNode() {}

// ID of the object.
func (this Prefecture) GetID() string { return this.ID }

type Program struct {
	AnnictID    int64        `json:"annictId"`
	Channel     *Channel     `json:"channel"`
	Episode     *Episode     `json:"episode"`
	ID          string       `json:"id"`
	Rebroadcast bool         `json:"rebroadcast"`
	ScPid       *int64       `json:"scPid,omitempty"`
	StartedAt   string       `json:"startedAt"`
	State       ProgramState `json:"state"`
	Work        *Work        `json:"work"`
}

func (Program) IsNode() {}

// ID of the object.
func (this Program) GetID() string { return this.ID }

// The connection type for Program.
type ProgramConnection struct {
	// A list of edges.
	Edges []*ProgramEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Program `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type ProgramEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Program `json:"node,omitempty"`
}

type ProgramOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     ProgramOrderField `json:"field"`
}

type Query struct {
}

type Record struct {
	AnnictID           int64        `json:"annictId"`
	Comment            *string      `json:"comment,omitempty"`
	CommentsCount      int64        `json:"commentsCount"`
	CreatedAt          string       `json:"createdAt"`
	Episode            *Episode     `json:"episode"`
	FacebookClickCount int64        `json:"facebookClickCount"`
	ID                 string       `json:"id"`
	LikesCount         int64        `json:"likesCount"`
	Modified           bool         `json:"modified"`
	Rating             *float64     `json:"rating,omitempty"`
	RatingState        *RatingState `json:"ratingState,omitempty"`
	TwitterClickCount  int64        `json:"twitterClickCount"`
	UpdatedAt          string       `json:"updatedAt"`
	User               *User        `json:"user"`
	Work               *Work        `json:"work"`
}

func (Record) IsActivityItem() {}

func (Record) IsNode() {}

// ID of the object.
func (this Record) GetID() string { return this.ID }

// The connection type for Record.
type RecordConnection struct {
	// A list of edges.
	Edges []*RecordEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Record `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type RecordEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Record `json:"node,omitempty"`
}

type RecordOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     RecordOrderField `json:"field"`
}

type Review struct {
	AnnictID             int64        `json:"annictId"`
	Body                 string       `json:"body"`
	CreatedAt            string       `json:"createdAt"`
	ID                   string       `json:"id"`
	ImpressionsCount     int64        `json:"impressionsCount"`
	LikesCount           int64        `json:"likesCount"`
	ModifiedAt           *string      `json:"modifiedAt,omitempty"`
	RatingAnimationState *RatingState `json:"ratingAnimationState,omitempty"`
	RatingCharacterState *RatingState `json:"ratingCharacterState,omitempty"`
	RatingMusicState     *RatingState `json:"ratingMusicState,omitempty"`
	RatingOverallState   *RatingState `json:"ratingOverallState,omitempty"`
	RatingStoryState     *RatingState `json:"ratingStoryState,omitempty"`
	Title                *string      `json:"title,omitempty"`
	UpdatedAt            string       `json:"updatedAt"`
	User                 *User        `json:"user"`
	Work                 *Work        `json:"work"`
}

func (Review) IsActivityItem() {}

func (Review) IsNode() {}

// ID of the object.
func (this Review) GetID() string { return this.ID }

// The connection type for Review.
type ReviewConnection struct {
	// A list of edges.
	Edges []*ReviewEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Review `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type ReviewEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Review `json:"node,omitempty"`
}

type ReviewOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     ReviewOrderField `json:"field"`
}

type Series struct {
	AnnictID int64                 `json:"annictId"`
	ID       string                `json:"id"`
	Name     string                `json:"name"`
	NameEn   string                `json:"nameEn"`
	NameRo   string                `json:"nameRo"`
	Works    *SeriesWorkConnection `json:"works,omitempty"`
}

func (Series) IsNode() {}

// ID of the object.
func (this Series) GetID() string { return this.ID }

// The connection type for Series.
type SeriesConnection struct {
	// A list of edges.
	Edges []*SeriesEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Series `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type SeriesEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Series `json:"node,omitempty"`
}

// The connection type for Work.
type SeriesWorkConnection struct {
	// A list of edges.
	Edges []*SeriesWorkEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Work `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type SeriesWorkEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	Item   *Work  `json:"item"`
	// The item at the end of the edge.
	Node      *Work   `json:"node,omitempty"`
	Summary   *string `json:"summary,omitempty"`
	SummaryEn *string `json:"summaryEn,omitempty"`
}

type SeriesWorkOrder struct {
	Direction OrderDirection       `json:"direction"`
	Field     SeriesWorkOrderField `json:"field"`
}

type Staff struct {
	AnnictID    int64             `json:"annictId"`
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	NameEn      string            `json:"nameEn"`
	Resource    StaffResourceItem `json:"resource"`
	RoleOther   string            `json:"roleOther"`
	RoleOtherEn string            `json:"roleOtherEn"`
	RoleText    string            `json:"roleText"`
	SortNumber  int64             `json:"sortNumber"`
	Work        *Work             `json:"work"`
}

func (Staff) IsNode() {}

// ID of the object.
func (this Staff) GetID() string { return this.ID }

// The connection type for Staff.
type StaffConnection struct {
	// A list of edges.
	Edges []*StaffEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Staff `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type StaffEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Staff `json:"node,omitempty"`
}

type StaffOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     StaffOrderField `json:"field"`
}

type Status struct {
	AnnictID   int64       `json:"annictId"`
	CreatedAt  string      `json:"createdAt"`
	ID         string      `json:"id"`
	LikesCount int64       `json:"likesCount"`
	State      StatusState `json:"state"`
	User       *User       `json:"user"`
	Work       *Work       `json:"work"`
}

func (Status) IsActivityItem() {}

func (Status) IsNode() {}

// ID of the object.
func (this Status) GetID() string { return this.ID }

// Autogenerated input type of UpdateRecord
type UpdateRecordInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string      `json:"clientMutationId,omitempty"`
	Comment          *string      `json:"comment,omitempty"`
	RatingState      *RatingState `json:"ratingState,omitempty"`
	RecordID         string       `json:"recordId"`
	ShareFacebook    *bool        `json:"shareFacebook,omitempty"`
	ShareTwitter     *bool        `json:"shareTwitter,omitempty"`
}

// Autogenerated return type of UpdateRecord.
type UpdateRecordPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Record           *Record `json:"record,omitempty"`
}

// Autogenerated input type of UpdateReview
type UpdateReviewInput struct {
	Body string `json:"body"`
	// A unique identifier for the client performing the mutation.
	ClientMutationID     *string     `json:"clientMutationId,omitempty"`
	RatingAnimationState RatingState `json:"ratingAnimationState"`
	RatingCharacterState RatingState `json:"ratingCharacterState"`
	RatingMusicState     RatingState `json:"ratingMusicState"`
	RatingOverallState   RatingState `json:"ratingOverallState"`
	RatingStoryState     RatingState `json:"ratingStoryState"`
	ReviewID             string      `json:"reviewId"`
	ShareFacebook        *bool       `json:"shareFacebook,omitempty"`
	ShareTwitter         *bool       `json:"shareTwitter,omitempty"`
	Title                *string     `json:"title,omitempty"`
}

// Autogenerated return type of UpdateReview.
type UpdateReviewPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Review           *Review `json:"review,omitempty"`
}

// Autogenerated input type of UpdateStatus
type UpdateStatusInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string     `json:"clientMutationId,omitempty"`
	State            StatusState `json:"state"`
	WorkID           string      `json:"workId"`
}

// Autogenerated return type of UpdateStatus.
type UpdateStatusPayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	Work             *Work   `json:"work,omitempty"`
}

type User struct {
	Activities          *ActivityConnection     `json:"activities,omitempty"`
	AnnictID            int64                   `json:"annictId"`
	AvatarURL           *string                 `json:"avatarUrl,omitempty"`
	BackgroundImageURL  *string                 `json:"backgroundImageUrl,omitempty"`
	CreatedAt           string                  `json:"createdAt"`
	Description         string                  `json:"description"`
	Email               *string                 `json:"email,omitempty"`
	Followers           *UserConnection         `json:"followers,omitempty"`
	FollowersCount      int64                   `json:"followersCount"`
	Following           *UserConnection         `json:"following,omitempty"`
	FollowingActivities *ActivityConnection     `json:"followingActivities,omitempty"`
	FollowingsCount     int64                   `json:"followingsCount"`
	ID                  string                  `json:"id"`
	LibraryEntries      *LibraryEntryConnection `json:"libraryEntries,omitempty"`
	Name                string                  `json:"name"`
	NotificationsCount  *int64                  `json:"notificationsCount,omitempty"`
	OnHoldCount         int64                   `json:"onHoldCount"`
	Programs            *ProgramConnection      `json:"programs,omitempty"`
	Records             *RecordConnection       `json:"records,omitempty"`
	RecordsCount        int64                   `json:"recordsCount"`
	StopWatchingCount   int64                   `json:"stopWatchingCount"`
	URL                 *string                 `json:"url,omitempty"`
	Username            string                  `json:"username"`
	ViewerCanFollow     bool                    `json:"viewerCanFollow"`
	ViewerIsFollowing   bool                    `json:"viewerIsFollowing"`
	WannaWatchCount     int64                   `json:"wannaWatchCount"`
	WatchedCount        int64                   `json:"watchedCount"`
	WatchingCount       int64                   `json:"watchingCount"`
	Works               *WorkConnection         `json:"works,omitempty"`
}

func (User) IsNode() {}

// ID of the object.
func (this User) GetID() string { return this.ID }

// The connection type for User.
type UserConnection struct {
	// A list of edges.
	Edges []*UserEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*User `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type UserEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *User `json:"node,omitempty"`
}

// An anime title
type Work struct {
	AnnictID          int64              `json:"annictId"`
	Casts             *CastConnection    `json:"casts,omitempty"`
	Episodes          *EpisodeConnection `json:"episodes,omitempty"`
	EpisodesCount     int64              `json:"episodesCount"`
	ID                string             `json:"id"`
	Image             *WorkImage         `json:"image,omitempty"`
	MalAnimeID        *string            `json:"malAnimeId,omitempty"`
	Media             Media              `json:"media"`
	NoEpisodes        bool               `json:"noEpisodes"`
	OfficialSiteURL   *string            `json:"officialSiteUrl,omitempty"`
	OfficialSiteURLEn *string            `json:"officialSiteUrlEn,omitempty"`
	Programs          *ProgramConnection `json:"programs,omitempty"`
	Reviews           *ReviewConnection  `json:"reviews,omitempty"`
	ReviewsCount      int64              `json:"reviewsCount"`
	SatisfactionRate  *float64           `json:"satisfactionRate,omitempty"`
	SeasonName        *SeasonName        `json:"seasonName,omitempty"`
	SeasonYear        *int64             `json:"seasonYear,omitempty"`
	SeriesList        *SeriesConnection  `json:"seriesList,omitempty"`
	Staffs            *StaffConnection   `json:"staffs,omitempty"`
	SyobocalTid       *int64             `json:"syobocalTid,omitempty"`
	Title             string             `json:"title"`
	TitleEn           *string            `json:"titleEn,omitempty"`
	TitleKana         *string            `json:"titleKana,omitempty"`
	TitleRo           *string            `json:"titleRo,omitempty"`
	TwitterHashtag    *string            `json:"twitterHashtag,omitempty"`
	TwitterUsername   *string            `json:"twitterUsername,omitempty"`
	ViewerStatusState *StatusState       `json:"viewerStatusState,omitempty"`
	WatchersCount     int64              `json:"watchersCount"`
	WikipediaURL      *string            `json:"wikipediaUrl,omitempty"`
	WikipediaURLEn    *string            `json:"wikipediaUrlEn,omitempty"`
}

func (Work) IsNode() {}

// ID of the object.
func (this Work) GetID() string { return this.ID }

// The connection type for Work.
type WorkConnection struct {
	// A list of edges.
	Edges []*WorkEdge `json:"edges,omitempty"`
	// A list of nodes.
	Nodes []*Work `json:"nodes,omitempty"`
	// Information to aid in pagination.
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in a connection.
type WorkEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node *Work `json:"node,omitempty"`
}

type WorkImage struct {
	AnnictID               *int64  `json:"annictId,omitempty"`
	Copyright              *string `json:"copyright,omitempty"`
	FacebookOgImageURL     *string `json:"facebookOgImageUrl,omitempty"`
	ID                     string  `json:"id"`
	InternalURL            *string `json:"internalUrl,omitempty"`
	RecommendedImageURL    *string `json:"recommendedImageUrl,omitempty"`
	TwitterAvatarURL       *string `json:"twitterAvatarUrl,omitempty"`
	TwitterBiggerAvatarURL *string `json:"twitterBiggerAvatarUrl,omitempty"`
	TwitterMiniAvatarURL   *string `json:"twitterMiniAvatarUrl,omitempty"`
	TwitterNormalAvatarURL *string `json:"twitterNormalAvatarUrl,omitempty"`
	Work                   *Work   `json:"work,omitempty"`
}

func (WorkImage) IsNode() {}

// ID of the object.
func (this WorkImage) GetID() string { return this.ID }

type WorkOrder struct {
	Direction OrderDirection `json:"direction"`
	Field     WorkOrderField `json:"field"`
}

type ActivityAction string

const (
	ActivityActionCreate ActivityAction = "CREATE"
)

var AllActivityAction = []ActivityAction{
	ActivityActionCreate,
}

func (e ActivityAction) IsValid() bool {
	switch e {
	case ActivityActionCreate:
		return true
	}
	return false
}

func (e ActivityAction) String() string {
	return string(e)
}

func (e *ActivityAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityAction", str)
	}
	return nil
}

func (e ActivityAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ActivityOrderField string

const (
	ActivityOrderFieldCreatedAt ActivityOrderField = "CREATED_AT"
)

var AllActivityOrderField = []ActivityOrderField{
	ActivityOrderFieldCreatedAt,
}

func (e ActivityOrderField) IsValid() bool {
	switch e {
	case ActivityOrderFieldCreatedAt:
		return true
	}
	return false
}

func (e ActivityOrderField) String() string {
	return string(e)
}

func (e *ActivityOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityOrderField", str)
	}
	return nil
}

func (e ActivityOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CastOrderField string

const (
	CastOrderFieldCreatedAt  CastOrderField = "CREATED_AT"
	CastOrderFieldSortNumber CastOrderField = "SORT_NUMBER"
)

var AllCastOrderField = []CastOrderField{
	CastOrderFieldCreatedAt,
	CastOrderFieldSortNumber,
}

func (e CastOrderField) IsValid() bool {
	switch e {
	case CastOrderFieldCreatedAt, CastOrderFieldSortNumber:
		return true
	}
	return false
}

func (e CastOrderField) String() string {
	return string(e)
}

func (e *CastOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CastOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CastOrderField", str)
	}
	return nil
}

func (e CastOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CastOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CastOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CharacterOrderField string

const (
	CharacterOrderFieldCreatedAt               CharacterOrderField = "CREATED_AT"
	CharacterOrderFieldFavoriteCharactersCount CharacterOrderField = "FAVORITE_CHARACTERS_COUNT"
)

var AllCharacterOrderField = []CharacterOrderField{
	CharacterOrderFieldCreatedAt,
	CharacterOrderFieldFavoriteCharactersCount,
}

func (e CharacterOrderField) IsValid() bool {
	switch e {
	case CharacterOrderFieldCreatedAt, CharacterOrderFieldFavoriteCharactersCount:
		return true
	}
	return false
}

func (e CharacterOrderField) String() string {
	return string(e)
}

func (e *CharacterOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CharacterOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CharacterOrderField", str)
	}
	return nil
}

func (e CharacterOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CharacterOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CharacterOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EpisodeOrderField string

const (
	EpisodeOrderFieldCreatedAt  EpisodeOrderField = "CREATED_AT"
	EpisodeOrderFieldSortNumber EpisodeOrderField = "SORT_NUMBER"
)

var AllEpisodeOrderField = []EpisodeOrderField{
	EpisodeOrderFieldCreatedAt,
	EpisodeOrderFieldSortNumber,
}

func (e EpisodeOrderField) IsValid() bool {
	switch e {
	case EpisodeOrderFieldCreatedAt, EpisodeOrderFieldSortNumber:
		return true
	}
	return false
}

func (e EpisodeOrderField) String() string {
	return string(e)
}

func (e *EpisodeOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EpisodeOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EpisodeOrderField", str)
	}
	return nil
}

func (e EpisodeOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EpisodeOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EpisodeOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LibraryEntryOrderField string

const (
	// 最後に記録またはスキップした日時
	LibraryEntryOrderFieldLastTrackedAt LibraryEntryOrderField = "LAST_TRACKED_AT"
)

var AllLibraryEntryOrderField = []LibraryEntryOrderField{
	LibraryEntryOrderFieldLastTrackedAt,
}

func (e LibraryEntryOrderField) IsValid() bool {
	switch e {
	case LibraryEntryOrderFieldLastTrackedAt:
		return true
	}
	return false
}

func (e LibraryEntryOrderField) String() string {
	return string(e)
}

func (e *LibraryEntryOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LibraryEntryOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LibraryEntryOrderField", str)
	}
	return nil
}

func (e LibraryEntryOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LibraryEntryOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LibraryEntryOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Media of anime
type Media string

const (
	MediaMovie Media = "MOVIE"
	MediaOther Media = "OTHER"
	MediaOva   Media = "OVA"
	MediaTv    Media = "TV"
	MediaWeb   Media = "WEB"
)

var AllMedia = []Media{
	MediaMovie,
	MediaOther,
	MediaOva,
	MediaTv,
	MediaWeb,
}

func (e Media) IsValid() bool {
	switch e {
	case MediaMovie, MediaOther, MediaOva, MediaTv, MediaWeb:
		return true
	}
	return false
}

func (e Media) String() string {
	return string(e)
}

func (e *Media) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Media(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Media", str)
	}
	return nil
}

func (e Media) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Media) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Media) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrganizationOrderField string

const (
	OrganizationOrderFieldCreatedAt                  OrganizationOrderField = "CREATED_AT"
	OrganizationOrderFieldFavoriteOrganizationsCount OrganizationOrderField = "FAVORITE_ORGANIZATIONS_COUNT"
)

var AllOrganizationOrderField = []OrganizationOrderField{
	OrganizationOrderFieldCreatedAt,
	OrganizationOrderFieldFavoriteOrganizationsCount,
}

func (e OrganizationOrderField) IsValid() bool {
	switch e {
	case OrganizationOrderFieldCreatedAt, OrganizationOrderFieldFavoriteOrganizationsCount:
		return true
	}
	return false
}

func (e OrganizationOrderField) String() string {
	return string(e)
}

func (e *OrganizationOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationOrderField", str)
	}
	return nil
}

func (e OrganizationOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrganizationOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrganizationOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PersonOrderField string

const (
	PersonOrderFieldCreatedAt           PersonOrderField = "CREATED_AT"
	PersonOrderFieldFavoritePeopleCount PersonOrderField = "FAVORITE_PEOPLE_COUNT"
)

var AllPersonOrderField = []PersonOrderField{
	PersonOrderFieldCreatedAt,
	PersonOrderFieldFavoritePeopleCount,
}

func (e PersonOrderField) IsValid() bool {
	switch e {
	case PersonOrderFieldCreatedAt, PersonOrderFieldFavoritePeopleCount:
		return true
	}
	return false
}

func (e PersonOrderField) String() string {
	return string(e)
}

func (e *PersonOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PersonOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PersonOrderField", str)
	}
	return nil
}

func (e PersonOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PersonOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PersonOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProgramOrderField string

const (
	ProgramOrderFieldStartedAt ProgramOrderField = "STARTED_AT"
)

var AllProgramOrderField = []ProgramOrderField{
	ProgramOrderFieldStartedAt,
}

func (e ProgramOrderField) IsValid() bool {
	switch e {
	case ProgramOrderFieldStartedAt:
		return true
	}
	return false
}

func (e ProgramOrderField) String() string {
	return string(e)
}

func (e *ProgramOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgramOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgramOrderField", str)
	}
	return nil
}

func (e ProgramOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProgramOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProgramOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProgramState string

const (
	ProgramStateHidden    ProgramState = "HIDDEN"
	ProgramStatePublished ProgramState = "PUBLISHED"
)

var AllProgramState = []ProgramState{
	ProgramStateHidden,
	ProgramStatePublished,
}

func (e ProgramState) IsValid() bool {
	switch e {
	case ProgramStateHidden, ProgramStatePublished:
		return true
	}
	return false
}

func (e ProgramState) String() string {
	return string(e)
}

func (e *ProgramState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgramState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgramState", str)
	}
	return nil
}

func (e ProgramState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProgramState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProgramState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RatingState string

const (
	RatingStateAverage RatingState = "AVERAGE"
	RatingStateBad     RatingState = "BAD"
	RatingStateGood    RatingState = "GOOD"
	RatingStateGreat   RatingState = "GREAT"
)

var AllRatingState = []RatingState{
	RatingStateAverage,
	RatingStateBad,
	RatingStateGood,
	RatingStateGreat,
}

func (e RatingState) IsValid() bool {
	switch e {
	case RatingStateAverage, RatingStateBad, RatingStateGood, RatingStateGreat:
		return true
	}
	return false
}

func (e RatingState) String() string {
	return string(e)
}

func (e *RatingState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RatingState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RatingState", str)
	}
	return nil
}

func (e RatingState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RatingState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RatingState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecordOrderField string

const (
	RecordOrderFieldCreatedAt  RecordOrderField = "CREATED_AT"
	RecordOrderFieldLikesCount RecordOrderField = "LIKES_COUNT"
)

var AllRecordOrderField = []RecordOrderField{
	RecordOrderFieldCreatedAt,
	RecordOrderFieldLikesCount,
}

func (e RecordOrderField) IsValid() bool {
	switch e {
	case RecordOrderFieldCreatedAt, RecordOrderFieldLikesCount:
		return true
	}
	return false
}

func (e RecordOrderField) String() string {
	return string(e)
}

func (e *RecordOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecordOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecordOrderField", str)
	}
	return nil
}

func (e RecordOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecordOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecordOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReviewOrderField string

const (
	ReviewOrderFieldCreatedAt  ReviewOrderField = "CREATED_AT"
	ReviewOrderFieldLikesCount ReviewOrderField = "LIKES_COUNT"
)

var AllReviewOrderField = []ReviewOrderField{
	ReviewOrderFieldCreatedAt,
	ReviewOrderFieldLikesCount,
}

func (e ReviewOrderField) IsValid() bool {
	switch e {
	case ReviewOrderFieldCreatedAt, ReviewOrderFieldLikesCount:
		return true
	}
	return false
}

func (e ReviewOrderField) String() string {
	return string(e)
}

func (e *ReviewOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewOrderField", str)
	}
	return nil
}

func (e ReviewOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Season name
type SeasonName string

const (
	SeasonNameAutumn SeasonName = "AUTUMN"
	SeasonNameSpring SeasonName = "SPRING"
	SeasonNameSummer SeasonName = "SUMMER"
	SeasonNameWinter SeasonName = "WINTER"
)

var AllSeasonName = []SeasonName{
	SeasonNameAutumn,
	SeasonNameSpring,
	SeasonNameSummer,
	SeasonNameWinter,
}

func (e SeasonName) IsValid() bool {
	switch e {
	case SeasonNameAutumn, SeasonNameSpring, SeasonNameSummer, SeasonNameWinter:
		return true
	}
	return false
}

func (e SeasonName) String() string {
	return string(e)
}

func (e *SeasonName) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SeasonName(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SeasonName", str)
	}
	return nil
}

func (e SeasonName) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SeasonName) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SeasonName) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SeriesWorkOrderField string

const (
	SeriesWorkOrderFieldSeason SeriesWorkOrderField = "SEASON"
)

var AllSeriesWorkOrderField = []SeriesWorkOrderField{
	SeriesWorkOrderFieldSeason,
}

func (e SeriesWorkOrderField) IsValid() bool {
	switch e {
	case SeriesWorkOrderFieldSeason:
		return true
	}
	return false
}

func (e SeriesWorkOrderField) String() string {
	return string(e)
}

func (e *SeriesWorkOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SeriesWorkOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SeriesWorkOrderField", str)
	}
	return nil
}

func (e SeriesWorkOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SeriesWorkOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SeriesWorkOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StaffOrderField string

const (
	StaffOrderFieldCreatedAt  StaffOrderField = "CREATED_AT"
	StaffOrderFieldSortNumber StaffOrderField = "SORT_NUMBER"
)

var AllStaffOrderField = []StaffOrderField{
	StaffOrderFieldCreatedAt,
	StaffOrderFieldSortNumber,
}

func (e StaffOrderField) IsValid() bool {
	switch e {
	case StaffOrderFieldCreatedAt, StaffOrderFieldSortNumber:
		return true
	}
	return false
}

func (e StaffOrderField) String() string {
	return string(e)
}

func (e *StaffOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StaffOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StaffOrderField", str)
	}
	return nil
}

func (e StaffOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StaffOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StaffOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StatusState string

const (
	StatusStateNoState      StatusState = "NO_STATE"
	StatusStateOnHold       StatusState = "ON_HOLD"
	StatusStateStopWatching StatusState = "STOP_WATCHING"
	StatusStateWannaWatch   StatusState = "WANNA_WATCH"
	StatusStateWatched      StatusState = "WATCHED"
	StatusStateWatching     StatusState = "WATCHING"
)

var AllStatusState = []StatusState{
	StatusStateNoState,
	StatusStateOnHold,
	StatusStateStopWatching,
	StatusStateWannaWatch,
	StatusStateWatched,
	StatusStateWatching,
}

func (e StatusState) IsValid() bool {
	switch e {
	case StatusStateNoState, StatusStateOnHold, StatusStateStopWatching, StatusStateWannaWatch, StatusStateWatched, StatusStateWatching:
		return true
	}
	return false
}

func (e StatusState) String() string {
	return string(e)
}

func (e *StatusState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StatusState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StatusState", str)
	}
	return nil
}

func (e StatusState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StatusState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StatusState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkOrderField string

const (
	WorkOrderFieldCreatedAt     WorkOrderField = "CREATED_AT"
	WorkOrderFieldSeason        WorkOrderField = "SEASON"
	WorkOrderFieldWatchersCount WorkOrderField = "WATCHERS_COUNT"
)

var AllWorkOrderField = []WorkOrderField{
	WorkOrderFieldCreatedAt,
	WorkOrderFieldSeason,
	WorkOrderFieldWatchersCount,
}

func (e WorkOrderField) IsValid() bool {
	switch e {
	case WorkOrderFieldCreatedAt, WorkOrderFieldSeason, WorkOrderFieldWatchersCount:
		return true
	}
	return false
}

func (e WorkOrderField) String() string {
	return string(e)
}

func (e *WorkOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkOrderField", str)
	}
	return nil
}

func (e WorkOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
